title: Peticiones Abiertas
email: lets@populate.tools
org: Populate Tools
description: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PopulateTools
github_username: PopulateTools
lang: 'es'

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Collections
collections:
  peticiones:
    output: true
    permalink: /peticiones/:path

# Google Drive
gdrive:
  sheet: "Peticiones Abiertas"
  cache_period: 5 seconds